// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDevice } from "./AudioDevice";
import type { OverlayConfig } from "./OverlayConfig";

export type AppState = { running: boolean, current_device: AudioDevice, audio_buffer_size: number, overlay_config: OverlayConfig, };
