// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { AudioDevice } from "./AudioDevice";
import type { AudioFormat } from "./AudioFormat";
import type { OverlayConfig } from "./OverlayConfig";
import type { WhisperParams } from "./WhisperParams";

export type AppState = { current_device: AudioDevice, audio_format: AudioFormat, model_path: string, audio_segment_size: number, overlay_config: OverlayConfig, whisper_params: WhisperParams, advanced_settings: AdvancedSettings, };
