// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverlayConfig = { name: string, id: string, text_alignment: "left" | "center" | "right", background_color: string, transparency: number, };
