// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WhisperToggles = { translate: boolean, suppress_blanks: boolean, print_special: boolean, print_progress: boolean, token_timestamps: boolean, single_segment: boolean, split_on_word: boolean, tdrz_enable: boolean, };
