// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisperToggles } from "./WhisperToggles";

export type WhisperParams = { toggles: WhisperToggles, language: string, };
