// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisperText } from "./WhisperText";

export type WhisperSegment = { id: string, index: number, items: Array<WhisperText>, };
